### ISSUE TITLE
启动器的BUG？

### ISSUE THREAD

**Issue by MeiVinEight** [Moxiner/YuanShenEx_Launcher#4]
![image](https://user-images.githubusercontent.com/57023439/195967543-2d8bfce1-53fe-4a1c-bdbb-ef3926e34785.png)
![image](https://user-images.githubusercontent.com/57023439/195967538-c4bd65bd-7266-4d8b-87ba-f06c67be2845.png)
![image](https://user-images.githubusercontent.com/57023439/195967500-40d02b90-7e75-4e49-84b7-7d4f1c797428.jpg)
![image](https://user-images.githubusercontent.com/57023439/195967476-f6f504d4-3587-4307-a7f5-360c999e417f.jpg)
打开后出现了如图问题

**Comment by MeiVinEight** [comment]
![image](https://user-images.githubusercontent.com/57023439/195983816-6f3c4a98-62bd-44c2-bcee-9ae3f84cd827.png)
使用过启动器EX后原本的启动器检测不到游戏

**Comment by Moxiner** [comment]
已发布新版，虽然后续还有一个v1.2的大版本更新，但为了不影响使用，请先更新至 v1.1.2 版本！

**Comment by Moxiner** [comment]
> ![image](https://user-images.githubusercontent.com/57023439/195983816-6f3c4a98-62bd-44c2-bcee-9ae3f84cd827.png) 使用过启动器EX后原本的启动器检测不到游戏

这个我也不清楚是为什么（；´д｀）ゞ

**Comment by Moxiner** [comment]
> ![image](https://user-images.githubusercontent.com/57023439/195983816-6f3c4a98-62bd-44c2-bcee-9ae3f84cd827.png) 使用过启动器EX后原本的启动器检测不到游戏

请使用原神启动器Ex 先进一次游戏完成更新，退出后重新选择路径，官方启动器即可识别到！

**Comment by Moxiner** [comment]
请尽快回复，该 Issues 在 48小时 内未收到新的回复将会关闭！

**Comment by MeiVinEight** [comment]
暂未出现问题
