### ISSUE TITLE
一键修复后无法读取游戏版本

### ISSUE THREAD

**Issue by MChello1990** [Moxiner/YuanShenEx_Launcher#8]
用EX一键修复启动后官启再也无法读取游戏配置了 EX启动器能启动但是也显示读不出配置
![image](https://user-images.githubusercontent.com/30387541/202514413-9470128e-298f-4d20-8d0a-e2df9072beb0.png)
![image](https://user-images.githubusercontent.com/30387541/202514447-72a562c4-e2b8-42ba-86ae-ae1b5a98a095.png)
已尝试过上个issues里的解决方案 无效

**Comment by Moxiner** [comment]
请尝试重新安装原神启动器Ex，如果不行，请手动下载 [config.ini](https://github.com/Moxiner/YuanShenEx/blob/master/res/config.ini) 并替换游戏目录中 `Genshin Import Game ` 中，
如需使用 一键修复功能，请同时替换  `Genshin Import Game `  同级目录 `YuanShenEx / src / config.ini` 中！
||ヽ(*￣▽￣*)ノミ|Ю

**Comment by MChello1990** [comment]
问题已经修复 感谢开发大大
