### ISSUE TITLE
v1.1.7无法正常安装

### ISSUE THREAD

**Issue by NanNing00** [Moxiner/YuanShenEx_Launcher#9]
![屏幕截图 2023-04-19 023657](https://user-images.githubusercontent.com/131198104/232872008-114d16a0-ba7a-4f94-825e-9685369ef8a9.png)

**Comment by NanNing00** [comment]
进度条卡在这就不动了

**Comment by NanNing00** [comment]
替换旧版install.exe可以成功安装

**Comment by Moxiner** [comment]
已修复
